# 2012-2023년 수출입실적 & 품목명-품목코드 매핑 데이터

In [1]:
import os
import pickle
import numpy as np
import pandas as pd
from IPython.display import display
from tqdm import tqdm
tqdm.pandas()

import warnings
warnings.filterwarnings('ignore')

In [16]:
# 수출 실적 데이터 불러오기
performance = pd.DataFrame()
df_type = {'수출중량': 'float64', '수입중량': 'float64',
           '수출금액': 'float64', '수입금액': 'float64', '무역수지': 'float64'}

for file in tqdm(os.listdir('../data/품목별 국가별 수출입실적_2012-2023')):
    if file.endswith('.xls') or file.endswith('.xlsx'):
        try:
            data = pd.read_excel('../data/품목별 국가별 수출입실적_2012-2023/' + file,
                                 thousands=',', dtype=df_type)
            performance = pd.concat([performance, data])
        except Exception as e:
            print(f"Error reading file: {file}. Error message: {str(e)}")

100%|██████████| 105/105 [00:08<00:00, 12.69it/s]

In [17]:
display(performance.shape)
display(performance.head())

(148648, 9)

,기간,품목명,품목코드,국가명,수출중량,수입중량,수출금액,수입금액,무역수지
0,2014,살아 있는 동물,1.0,세이쉘,0.0,0.0,0.0,0.0,0.0
1,2014,어류ㆍ갑각류ㆍ연체동물과 그 밖의 수생(水生) 무척추동물,3.0,세이쉘,2578.9,521.8,3926.0,3043.0,883.0
2,2014,식용의 채소ㆍ뿌리ㆍ괴경(塊莖),7.0,세르비아,0.0,0.2,0.0,1.0,-1.0
3,2014,"식용의 과실과 견과류, 감귤류ㆍ멜론의 껍질",8.0,세르비아,0.0,77.3,0.0,741.0,-741.0
4,2014,커피ㆍ차ㆍ마테(maté)ㆍ향신료,9.0,세르비아,0.0,0.0,0.0,0.0,0.0

In [18]:
performance.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148648 entries, 0 to 603
Data columns (total 9 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   기간      148648 non-null  object
 1   품목명     148647 non-null  object
 2   품목코드    148647 non-null  float64
 3   국가명     148647 non-null  object
 4   수출중량    148648 non-null  float64
 5   수입중량    148648 non-null  float64
 6   수출금액    148648 non-null  float64
 7   수입금액    148648 non-null  float64
 8   무역수지    148648 non-null  float64
dtypes: float64(6), object(3)
memory usage: 11.3+ MB

In [19]:
performance['기간'].unique()

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2013,
       2012, '총계', '2019', '2020', '2021', '2022', '2023'], dtype=object)

In [20]:
# 총계 데이터 제거
performance = performance.query('기간 != "총계"')
performance['기간'] = performance['기간'].astype('int64')

In [21]:
performance.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
기간,148647.0,NaN,NaN,NaN,2017.521403,3.395141,2012.0,2015.0,2018.0,2020.0,2023.0
품목명,148647,96,"전기기기와 그 부분품, 녹음기ㆍ음성 재생기ㆍ텔레비전의 영상과 음성의 기록기ㆍ재생기와...",2821,NaN,NaN,NaN,NaN,NaN,NaN,NaN
품목코드,148647.0,NaN,NaN,NaN,51.155207,27.342033,1.0,28.0,52.0,74.0,99.0
국가명,148647,253,홍콩,1618,NaN,NaN,NaN,NaN,NaN,NaN,NaN
수출중량,148647.0,NaN,NaN,NaN,15433.732577,232793.773518,0.0,0.1,10.1,296.8,18728239.2
수입중량,148647.0,NaN,NaN,NaN,47718.237855,1141072.808278,0.0,0.0,0.1,67.5,73468591.8
수출금액,148647.0,NaN,NaN,NaN,45731.265542,716609.576789,0.0,2.0,90.0,1784.0,72444995.0
수입금액,148647.0,NaN,NaN,NaN,41281.780224,588507.58314,0.0,0.0,3.0,637.0,56044458.0
무역수지,148647.0,NaN,NaN,NaN,4449.480117,592144.287789,-39864815.0,-14.0,11.0,607.0,33302901.0

In [22]:
print(sorted(performance['기간'].unique()))
print(sorted(performance['품목명'].unique()))
print(sorted(performance['품목코드'].unique()))
print(sorted(performance['국가명'].unique()))

[2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
['가구, 침구ㆍ매트리스ㆍ매트리스 서포트(mattress support)ㆍ쿠션과 이와 유사한 물품, 다른 류로 분류되지 않은 조명기구, 조명용 사인ㆍ조명용 네임플레이트(name-plate)와 이와 유사한 물품, 조립식 건축물', '가죽제품, 마구, 여행용구ㆍ핸드백과 이와 유사한 용기, 동물 거트(gut)[누에의 거트(gut)는 제외한다]의 제품', '각종 조제 식료품', '각종 화학공업 생산품', '견', '고무와 그 제품', '곡물', '곡물ㆍ고운 가루ㆍ전분ㆍ밀크의 조제품과 베이커리 제품', '광(鑛)ㆍ슬래그(slag)ㆍ회(灰)', '광물성 연료ㆍ광물유(鑛物油)와 이들의 증류물, 역청(瀝靑)물질, 광물성 왁스', '광학기기ㆍ사진용 기기ㆍ영화용 기기ㆍ측정기기ㆍ검사기기ㆍ정밀기기ㆍ의료용 기기, 이들의 부분품과 부속품', '구리와 그 제품', '그 밖의 비금속(卑金屬), 서멧(cermet), 이들의 제품', '그 밖의 식물성 방직용 섬유, 종이실(paper yarn)과 종이실로 만든 직물', '낙농품, 새의 알, 천연꿀, 다른 류로 분류되지 않은 식용인 동물성 생산품', '납과 그 제품', '니켈과 그 제품', '다른 류로 분류되지 않은 동물성 생산품', '단백질계 물질, 변성전분, 글루(glue), 효소', '담배와 제조한 담배 대용물, 연소시키지 않고흡입하도록 만들어진 물품(니코틴을 함유하였는지에 상관없다), 니코틴을 함유한 그 밖의 물품으로 인체 내에 니코틴을 흡수시키도록 만들어진 것', '당류(糖類)와 설탕과자', '도자제품', '돌ㆍ플라스터(plaster)ㆍ시멘트ㆍ석면ㆍ운모나 이와 유사한 재료의 제품', '동물성ㆍ식물성ㆍ미생물성 지방과 기름 및이들의 분해생산물, 조제한 식용 지방과 동물성ㆍ식물성 왁스', '락(lac), 검ㆍ수지ㆍ그 밖의 식물성 수액과 추출물(extract)', '메리야스 편물과 뜨개질 편물', '면', '모자류와 그 부분품', '모피ㆍ인조모피와 이들의 제품', '목재나 그 밖의 섬유질 셀룰로오스재료의 펄프, 회수한 종이ㆍ판지[웨이스트(waste)와 스크랩(scrap)]', '목재와 그 제품, 목탄', '무기화학품, 귀금속ㆍ희토류(稀土類)금속ㆍ방사성원소ㆍ동위원소의 유기화합물이나 무기화합물', '비금속(卑金屬)으로 만든 각종 제품', '비금속(卑金屬)으로 만든 공구ㆍ도구ㆍ칼붙이ㆍ스푼ㆍ포크, 이들의 부분품', '비누ㆍ유기계면활성제ㆍ조제 세제ㆍ조제 윤활제ㆍ인조 왁스ㆍ조제 왁스ㆍ광택용이나 연마용 조제품ㆍ양초와 이와 유사한 물품ㆍ조형용 페이스트(paste)ㆍ치과용 왁스와 플라스터(plaster)를 기본 재료로 한 치과용 조제품', '비료', '사진용이나 영화용 재료', '산류(傘類)ㆍ지팡이ㆍ시트스틱(seat-stick)ㆍ채찍ㆍ승마용 채찍과 이들의 부분품', '살아 있는 동물', '살아 있는 수목과 그 밖의 식물, 인경(鱗莖)ㆍ뿌리와 이와 유사한 물품, 절화(切花)와 장식용 잎', '선박과 수상 구조물', '소금, 황, 토석류(土石類), 석고ㆍ석회ㆍ시멘트', '시계와 그 부분품', '식물성 편조물(編組物)용 재료와 다른 류로 분류되지 않은 식물성 생산품', '식용의 과실과 견과류, 감귤류ㆍ멜론의 껍질', '식용의 채소ㆍ뿌리ㆍ괴경(塊莖)', '식품 공업에서 생기는 잔재물과 웨이스트(waste), 조제 사료', '신발류ㆍ각반과 이와 유사한 것, 이들의 부분품', '아연과 그 제품', '악기와 그 부분품과 부속품', '알루미늄과 그 제품', '양모ㆍ동물의 부드러운 털이나 거친 털ㆍ말의 털로 만든 실과 직물', '양탄자류와 그 밖의 방직용 섬유로 만든 바닥깔개', '어류ㆍ갑각류ㆍ연체동물과 그 밖의 수생(水生) 무척추동물', '예술품ㆍ수집품ㆍ골동품', '완구ㆍ게임용구ㆍ운동용구와 이들의 부분품과 부속품', '워딩(wadding)ㆍ펠트(felt)ㆍ부직포, 특수사, 끈ㆍ배의 밧줄(cordage)ㆍ로프ㆍ케이블과 이들의 제품', '원자로ㆍ보일러ㆍ기계류와 이들의 부분품', '원피(모피는 제외한다)와 가죽', '유기화학품', '유리와 유리제품', '유연용ㆍ염색용 추출물(extract), 탄닌과 이들의 유도체, 염료ㆍ안료와 그 밖의 착색제, 페인트ㆍ바니시(varnish), 퍼티(putty)와 그 밖의 매스틱(mastic), 잉크', '육과 식용 설육(屑肉)', '육류ㆍ어류ㆍ갑각류ㆍ연체동물이나 그 밖의 수생(水生) 무척추동물 또는 곤충의 조제품', '음료ㆍ주류ㆍ식초', '의료용품', '의류와 그 부속품(메리야스 편물이나 뜨개질 편물로 한정한다)', '의류와 그 부속품(메리야스 편물이나 뜨개질편물은 제외한다)', '인쇄서적ㆍ신문ㆍ회화ㆍ그 밖의 인쇄물, 수제(手製)문서ㆍ타자문서ㆍ도면', '인조스테이플섬유', '인조필라멘트, 인조방직용 섬유재료의 스트립(strip)과 이와 유사한 것', '입법 ; 설치된 간이 수정에 따른 입법을 트레이드한다 ; 추가적 수입제한농업인 것의 제 22 부에 따른 확립된 것 조정 행위, 수정된 것처럼', '잡품', '전기기기와 그 부분품, 녹음기ㆍ음성 재생기ㆍ텔레비전의 영상과 음성의 기록기ㆍ재생기와 이들의 부분품ㆍ부속품', '정유(essential oil)와 레지노이드(resinoid), 조제향료와 화장품ㆍ화장용품', '제분공업의 생산품과 맥아, 전분, 이눌린(inulin), 밀의 글루텐(gluten)', '제품으로 된 방직용 섬유의 그 밖의 물품, 세트, 사용하던 의류ㆍ방직용 섬유제품, 넝마', '조제 깃털ㆍ솜털과 그 제품, 조화, 사람 머리카락으로 된 제품', '종이와 판지, 제지용 펄프ㆍ종이ㆍ판지의 제품', '주석과 그 제품', '짚ㆍ에스파르토(esparto)나 그 밖의 조물 재료의 제품, 바구니 세공물(basketware)과 지조세공물(枝條細工物)', '채소ㆍ과실ㆍ견과류나 식물의그 밖의 부분의 조제품', '채유(採油)에 적합한 종자와 과실, 각종 종자와 과실, 공업용ㆍ의약용 식물, 짚과 사료용 식물', '천연진주ㆍ양식진주ㆍ귀석ㆍ반귀석ㆍ귀금속ㆍ귀금속을 입힌 금속과 이들의 제품, 모조 신변장식용품, 주화', '철강', '철강의 제품', '철도용이나 궤도용 기관차ㆍ차량과 이들의 부분품, 철도용이나 궤도용 장비품과 그 부분품, 기계식(전기기계식을 포함한다) 각종 교통신호용 기기', '철도용이나 궤도용 외의 차량과 그 부분품ㆍ부속품', '침투ㆍ도포ㆍ피복하거나 적층한 방직용 섬유의 직물, 공업용인 방직용 섬유제품', '커피ㆍ차ㆍ마테(maté)ㆍ향신료', '코르크(cork)와 그 제품', '코코아와 그 조제품', '특수직물, 터프트(tuft)한 직물, 레이스, 태피스트리(tapestry), 트리밍(trimming), 자수천', '플라스틱과 그 제품', '항공기와 우주선, 이들의 부분품', '화약류, 화공품, 성냥, 발화성 합금, 특정 가연성 조제품']
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 94.0, 95.0, 96.0, 97.0, 99.0]
['가나', '가봉', '가이아나', '감비아', '건지', '과델로프', '과테말라', '괌', '교황청', '국제통화기금', '그레나다', '그리스', '그린랜드', '기네비소', '기니', '기타국', '나미비아', '나우루', '나이지리아', '남수단', '남아프리카공화국', '남조지아 & 남샌드위치 군도', '네덜란드', '네덜란드 열도', '네팔', '노르웨이', '노폴크 아일랜드', '뉴 칼레도니아', '뉴질랜드', '니우에', '니제르', '니카라과', '대만', '덴마크', '도미니카', '도미니카 공화국', '독일', '라오스', '라이베리아', '라트비아', '러시아 연방', '레바논', '레소토', '루마니아', '룩셈부르그', '르완다', '리비아', '리투아니아', '리히텐슈타인', '마다카스카르', '마샬군도', '마세도니아', '마이너 아우틀링 합중국 군도', '마이크로네시아', '마카오', '마티니크', '말라위', '말레이시아', '말리', '맨섬', '메요트', '멕시코', '모나코', '모로코', '모리셔스', '모리타니', '모잠비크', '몬테네그로', '몬트세라트', '몰도바', '몰디브', '몰타', '몽골', '미국', '미령 버진군도', '미얀마', '바누아투', '바레인', '바베이도스', '바하마', '방글라데시', '버뮤다', '베네주엘라', '베닝', '베라루스', '베트남', '벨기에', '벨라루스', '벨리제', '보네르 신트외스타티위스', '보빗군도', '보스니아-헤르체고비나', '보츠와나', '볼리비아', '부룬디', '부르키나 파소', '부탄', '북마리아나 군도', '불가리아', '불령 가이아나', '불령 남부지역', '불령 리유니온 코모도 제도', '불령 폴리네시아', '브라질', '브루나이', '사모아', '사우디아라비아', '사이프러스', '산마리노', '상토메 프린스페', '서사하라', '세네갈', '세르비아', '세이쉘', '세인트 루시아', '세인트 마틴', '세인트 바르탤르미', '세인트 빈센트 그레나딘', '세인트 키츠 네비스', '세인트 피레 미켈론', '세인트 헬레나', '세인트마틴(생마르탱)', '소말리아', '솔로몬 군도', '수단', '수리남', '스리랑카', '스발비드 군도', '스와질랜드', '스웨덴', '스위스', '스페인', '슬로바키아', '슬로베니아', '시리아', '시에라 리온', '싱가포르', '아랍에미리트 연합', '아루바', '아르메니아', '아르헨티나', '아메리칸 사모아', '아이슬란드', '아이티', '아일랜드', '아제르바이잔', '아프카니스탄', '안도라', '안타티카', '안티가 바부다', '알랜드 군도', '알바니아', '알제리', '앙골라', '앙귈라', '에리트리아', '에스토니아', '에쿠아도르', '에티오피아', '엘살바도르', '영국', '영령 버진군도', '영령 인도양', '영령 캐이맨 군도', '예맨', '오만', '오스트리아', '온두라스', '왈라스 & 퓨투나 군도', '요르단', '우간다', '우루과이', '우즈베키스탄', '우크라이나', '이라크', '이란', '이스라엘', '이집트', '이탈리아', '인도', '인도네시아', '일본', '자마이카', '자이르', '잠비아', '저어지', '적도 기니', '조지아', '중국', '중앙아프리카공화국', '지부티', '지브랄타', '짐바브웨', '챠드', '체코공화국', '칠레', '카메룬', '카보 베르데', '카자흐스탄', '카타르', '캄보디아', '캐나다', '케냐', '코모로스', '코스 군도', '코스타리카', '코트디봐르', '콜롬비아', '콩고', '콩고민주공화국', '쿠바', '쿠웨이트', '쿡 아일랜드', '큐라소', '크로아티아', '크리스마스 아일랜드', '키르기스스탄', '키리바티', '타지크', '탄자니아', '태국', '토고', '토켈라우', '통가', '투르크 & 카이코스 군도', '투르크멘', '투발루', '튀니지', '튀르키예', '트리니다드 토바고', '티모르', '파나마', '파라과이', '파로에 군도', '파키스탄', '파푸아 뉴기니', '팔라우', '팔레스타인 해방기구', '페루', '포루투갈', '포클랜드 군도', '폴란드', '푸에르토리코', '프랑스', '피지', '피트카이른', '핀란드', '필리핀', '해외교포', '허드 앤 맥도날드 군도', '헝가리', '호주', '홍콩']

In [23]:
print('총 국가 수:', len(performance['국가명'].unique()))
print('총 품목 수:', len(performance['품목코드'].unique()))

총 국가 수: 253
총 품목 수: 96

In [24]:
# 2023년은 아직 1년이 다 차지 않았기 때문에 제외
performance = performance.query('기간 != 2023')
sorted(performance['기간'].unique())

[2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [25]:
# 기간, 국가명, 품목코드 순으로 정렬
performance.sort_values(by=['기간', '국가명', '품목코드'], inplace=True)
performance.head()

,기간,품목명,품목코드,국가명,수출중량,수입중량,수출금액,수입금액,무역수지
1,2012,살아 있는 동물,1.0,가나,0.0,0.0,0.0,3.0,-3.0
3,2012,육과 식용 설육(屑肉),2.0,가나,1.5,0.0,30.0,0.0,30.0
6,2012,어류ㆍ갑각류ㆍ연체동물과 그 밖의 수생(水生) 무척추동물,3.0,가나,2449.7,1775.9,2334.0,6202.0,-3868.0
10,2012,다른 류로 분류되지 않은 동물성 생산품,5.0,가나,0.0,0.0,0.0,9.0,-9.0
16,2012,커피ㆍ차ㆍ마테(maté)ㆍ향신료,9.0,가나,0.1,0.0,11.0,0.0,11.0

In [26]:
# performance 피클 파일로 압축 저장
with open('../processed/performance_2012-2023.pkl', 'wb') as f:
    pickle.dump(performance, f, pickle.HIGHEST_PROTOCOL)

In [27]:
item_name_code = performance[['품목명', '품목코드']].drop_duplicates().sort_values(by='품목코드')
item_name_code

                                                    품목명  품목코드
1                                              살아 있는 동물   1.0
3                                          육과 식용 설육(屑肉)   2.0
6                        어류ㆍ갑각류ㆍ연체동물과 그 밖의 수생(水生) 무척추동물   3.0
9             낙농품, 새의 알, 천연꿀, 다른 류로 분류되지 않은 식용인 동물성 생산품   4.0
10                                다른 류로 분류되지 않은 동물성 생산품   5.0
...                                                 ...   ...
294   가구, 침구ㆍ매트리스ㆍ매트리스 서포트(mattress support)ㆍ쿠션과 이와 ...  94.0
302                          완구ㆍ게임용구ㆍ운동용구와 이들의 부분품과 부속품  95.0
306                                                  잡품  96.0
307                                         예술품ㆍ수집품ㆍ골동품  97.0
1665  입법 ; 설치된 간이 수정에 따른 입법을 트레이드한다 ; 추가적 수입제한농업인 것의...  99.0

[96 rows x 2 columns]

In [28]:
# 품목명-품목코드 매핑 데이터 따로 저장
item_name_code.to_csv('../processed/item_name-code.csv', index=False)